root_file = 'E:/tensorflow_workspace/two_stream_zhuc/'
dataset_file = root_file + 'UCF101/'
split_file = root_file + 'ucfTrainTestlist/'
flow_file = root_file + 'flow/'
data_file = root_file + 'data/'